config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :items do
    resources :bookings, only: [ :new, :create, :edit, :update, :destroy ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
  mount Attachinary::Engine => "/attachinary"

  get "dashboard", to: "items#dashboard", as: :dashboard
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "Flatlay.JPG" %>');">
  <div class="banner-content">
    <h1>Are You A Dapper Dan?</h1>
    <p>A luxury menswear accessories rental platform</p>
    <p>...because $300 for a tie you'll only wear once sucks.</p>
    <%= form_tag(items_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], class: 'banner-searchbar', placeholder: 'Search' %>
      <%= submit_tag 'Search', name: nil, class: "btn-search" %>
    <% end %>
  </div>
</div>
<!--VALUE PROP-->
<div class="value-prop">
  <div class="drab">
    <%= image_tag "figures-03.png", class: "figure" %>
    <h3>Looking a little drab</h3>
      <h3>these days?</h3>
  </div>
  <div class="us">
    <%= image_tag "figures-02.png", class: "figure" %>
    <h3>Head to Dapper Dan to quickly</h3>
    <h3>rent luxury men’s accessories</h3>
  </div>
  <div class="dapper">
    <%= image_tag "figures-01.png", class: "figure" %>
    <h3>Cue the compliments</h3>
  </div>
</div>

<!-- CARDS -->
<!-- Tie Cards -->
<div class="container home-cards">
  <div class="category-title">
    <h2>TIES</h2>
    <%= link_to "See All", items_path %>
  </div>
  <div class="row">
    <% @ties.each do |tie| %>
    <div class="col col-sm-4 ">
      <%= link_to item_path(tie), class: "card-link" do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= tie.photo? ? (cl_image_path tie.photo.path) : (image_path 'Flatlay.JPG') %>');">
      <% end %>
        <div class="card-category"><%= tie.category %></div>
        <div class="card-description">
          <p><%= tie.brand %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<!-- Shades Cards -->
<div class="container home-cards">
  <div class="category-title">
    <h2>SHADES</h2>
    <%= link_to "See All", items_path %>
  </div>
  <div class="row">
    <% @shades.each do |shade| %>
    <div class="col col-sm-4 ">
      <%= link_to item_path(shade), class: "card-link" do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= shade.photo? ? (cl_image_path shade.photo.path) : (image_path 'Flatlay.JPG') %>');">
      <% end %>
        <div class="card-category"><%= shade.category %></div>
        <div class="card-description">
          <p><%= shade.brand %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<!-- Belts Cards -->
<div class="container home-cards">
  <div class="category-title">
    <h2>BELTS</h2>
    <%= link_to "See All", items_path %>
  </div>
  <div class="row">
    <% @belts.each do |belt| %>
    <div class="col col-sm-4 ">
      <%= link_to item_path(belt), class: "card-link" do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= belt.photo? ? (cl_image_path belt.photo.path) : (image_path 'Flatlay.JPG') %>');">
      <% end %>
        <div class="card-category"><%= belt.category %></div>
        <div class="card-description">
          <p><%= belt.brand %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class = "add-item">
  <h1>POST AN ITEM UP!</h1>
  <%= link_to "Add Item", new_item_path, class: "btn-add" %>
</div>