config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :items do
    resources :bookings, only: [ :new, :create, :edit, :update, :destroy ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
  mount Attachinary::Engine => "/attachinary"

  get "dashboard", to: "items#dashboard", as: :dashboard
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_attachment :photo

  has_many :bookings, dependent: :destroy
  # has_many :reviews, through: :bookings, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: ["bags", "jewellery", "fine watches", "belts", "ties", "shades", "hats", "pocket squares", "cufflinks"], allow_nil: false}
  validates :description, presence: true
  validates :condition, presence: true, inclusion: { in: ["perfect", "very good", "good", "worn well"]}
  validates :brand, presence: true
  validates :price, presence: true

  def self.search(search)
    if search
      # unless search.blank?
      # where('category LIKE ?', "%#{search}%")
      Item.where("category LIKE ? OR brand LIKE ?", "%#{search}%","%#{search}%")
    else
      all
    end
  end

  def self.brands
    ["A.P.C.","Acne Studios","Reem Acra","Aimé Leon Dore","Akris","Azzedine Alaïa","Reem Alasadi","Alexander McQueen","Balenciaga", "Gucci", "Saint-Laurent", "Versace, Zegna", "Givenchy", "Off-White", "Suit Supply", "Dior", "Louis Vuitton"]
  end
  def self.categories
    ["bags", "jewellery", "fine watches", "belts", "ties", "shades", "hats", "pocket squares", "cufflinks"]
  end

  def self.conditions
    ["perfect", "very good", "good", "worn well"]
  end

  def next_booked
    today = Date.today
    bookings.select { |b| b.start_date >= today }.first
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @items = Item.search(params[:search])
    @query = params[:search]
    @query_message = "You have searched: #{@query}"
    @preselect = {}

    s_params = params.permit("category", "brand", "condition").to_hash

    if s_params.size > 1
    # FILTERS BEGIN
    @items = @items.select{|i| i.brand == s_params["brand"]} unless s_params["brand"].blank?
    @items = @items.select{|i| i.category == s_params["category"]} unless s_params["category"].blank?
    @items = @items.select{|i| i.condition == s_params["condition"]} unless s_params["condition"].blank?

    else
      @search_cat = Item.categories.include?(params[:search]) ? "#{params[:search]}" : ""
      @search_brand = Item.brands.include?(params[:search]) ? "#{params[:search]}" : ""
      @preselect[:category] = @search_cat
      @preselect[:brand] = @search_brand
    end


    if @items.size == 0
      @items = Item.all
      @query_message = "There is no results! Search again..."
    end
    # if request.post?
    #   @items = @items.select{|i| i.category == search_params[:category]}
    # end

  end
# http://localhost:3000/items?params%5B%3Acategory%5D=belts&params%5B%3Abrand%5D=Alexander+McQueen+%28brand%29&params%5B%3Acondition%5D=good

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
    @booking = Booking.new
    # @user_coordinates = { latitude: @user.latitude, longitude: @user.longitude }
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
    @item = Item.new
    @user = current_user
  end

  def create
    @item = Item.new(params_item)
    @user = current_user
    @item.user = @user
    if @item.save
      redirect_to dashboard_path, notice: "Item added to system!"
    else
      render :new
    end
  end
  def edit
    @item = Item.find(params[:id])
    unless @item.user == current_user
      redirect_to dashboard_path, notice: "This isn't your item!"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(params_item)
    redirect_to dashboard_path, notice: "Your item was updated!"
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to dashboard_path, notice: "Your item was deleted!"
  end

  def dashboard
    #for renting out: show items, add items, edit items, update items, destroy items
    @user = current_user
    @my_items = @user.items
    #for renting: show bookings, edit bookings, update bookings, destroy bookings
    @my_bookings = @user.bookings
    #edit settings: display an edit form for user .... optional if we have time

  end

  private

  def params_item
    params.require(:item).permit(:name, :category, :description, :condition, :brand, :price, :user_id, :photo, :search)

  end

  def search_params
    params.require(:search).permit(:category, :condition, :brand, :price, :photo )
  end
end

app/views/items/_rent-out-tab.html.erb
<section id="content1">
  <!-- ADD ITEM button -->
  <div class="dashboard-button">
    <%= link_to "Add item", new_item_path, class: "btn btn-primary" %>
  </div>
  <!-- Cards -->
  <div class="container cards">
    <% if @my_items.count > 0 %>
      <div class="category-title">
        <h2><%= "Your Dapper Dan Items:" %></h2>
      </div>
    <% end %>
    <div class="row">
      <% @my_items.each do |item| %>
      <div class="col col-xs-12 col-sm-6">
        <div class="dashboard-card">
          <%= link_to item_path(item), class: "card-link" do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= item.photo? ? (cl_image_path item.photo.path) : (image_path 'Flatlay.JPG') %>');">
          <% end %>
            <div class="card-category"><%= item.name %></div>
          </div>
          <div class="card-info no-margin">
            <p><%= item.brand %></p>
            <p>￥<%= item.price %>/day</p>
          </div>
          <div class="edit-icons">
            <%= link_to root_path do %>
              <i class="fa fa-envelope" aria-hidden="true"></i>
            <% end %>
            <%= link_to edit_item_path(item) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= link_to "/items/#{item.id}", method: :delete,
          data: { confirm: "Are you sure you want to get rid of this item?" } do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="your-bookings"></div>
        </div>

        <% if item.next_booked %>
          <div class="your-bookings">
            <div>
              <h3><%= item.next_booked == nil ? "" : "Your item has a booking:" %></h3>
              <p><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <%= item.next_booked == nil ? "" : item.next_booked.start_date %></p>
              <p><i class="fa fa-calendar-times-o" aria-hidden="true"></i> <%= item.next_booked == nil ? "" : item.next_booked.end_date %></p>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</section>


<!--   ALL ITEM.NEXT_BOOKED (in <p> are meant to display bookings) -->

app/views/items/_renting.html.erb
<section id="content2">
  <div class="row">
    <% @my_bookings.each do |booking| %>
    <div class="col col-xs-12 col-sm-6">
      <div class="dashboard-card">
        <%= link_to item_path(booking.item), class: "card-link" do %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= booking.item.photo? ? (cl_image_path booking.item.photo.path) : (image_path 'Flatlay.JPG') %>');">
        <% end %>
          <div class="card-category"><%= booking.item.name %></div>
        </div>
        <div class="card-info no-margin">
          <p><%= booking.item.brand %></p>
          <p>￥<%= booking.item.price %>/day</p>
        </div>
        <div class="edit-icons">
            <%= link_to root_path do %>
              <i class="fa fa-envelope" aria-hidden="true"></i>
            <% end %>
            <%= link_to edit_item_booking_path(booking.item, booking) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= link_to item_booking_path(booking.item, booking), method: :delete,
  data: { confirm: "Are you sure you want to delete this booking?" } do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
        </div>
        <div class="bookings">
          <h3>Booked:</h3>
          <p><i class="fa fa-calendar-check-o" aria-hidden="true"></i>  <%= booking.start_date %>   </p>
          <p><i class="fa fa-calendar-times-o" aria-hidden="true"></i>  <%= booking.end_date %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/items/_settings.html.erb
<section id="content3">
<%= render "devise/shared/regform" %>
</section>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/dashboard.html.erb
<<<<<<< Updated upstream
<h1>Items#dashboard</h1>
<p>Find me in app/views/items/dashboard.html.erb</p>
=======
<div class="dashboard-header">
  <% avatar_url = current_user.facebook_picture_url || "bow-tie.png" %>
  <%= image_tag avatar_url, class: "avatar" %>
  <%= image_tag "dapper-dashboard.png", class: "header" %>
</div>

<main class="tabs">

  <input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1">Rented Out</label>

  <input id="tab2" type="radio" name="tabs">
  <label for="tab2">Renting</label>

  <input id="tab3" type="radio" name="tabs">
  <label for="tab3">Settings</label>

  <section id="content1">
    <div class="dashboard-button">
      <%= link_to "Add item", new_item_path, class: "btn btn-primary" %>
    </div>
    <div class="container cards">
      <div class="category-title">
        <h2><%= "You have added:" %></h2>
      </div>
      <div class="row">
        <% @my_items.each do |item| %>
        <div class="col col-xs-12 col-sm-4">
          <%= link_to item_path(item), class: "card-link" do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= item.photo? ? (cl_image_path item.photo.path) : (image_path 'Flatlay.JPG') %>');">
          <% end %>
            <div class="card-category"><%= item.name %></div>
          </div>
          <div class="card-info">
            <p><%= item.brand %></p>
            <p><%= item.price %></p>
          </div>
        </div>
        <p><%= link_to "Edit Item", edit_item_path(item) %></p>
        <p><%= link_to "Delete Item", "/items/#{item.id}", method: :delete,
      data: { confirm: "Are you sure you want to get rid of this item?" } %></p>
        <% end %>
      </div>
    </div>
  </section>

  <section id="content2">
      <div class="row">
        <% @my_bookings.each do |booking| %>
        <div class="col col-xs-12 col-sm-4">
        <div class="card-category"><%= booking.item.name %></div>
            <p><%= booking.start_date %></p>
            <p><%= booking.end_date %></p>
        </div>
        <p><%= link_to "Edit Booking", edit_item_booking_path(booking.item, booking) %></p>
        <p><%= link_to "Delete Booting", item_booking_path(booking.item, booking), method: :delete,
      data: { confirm: "Are you sure you want to delete this booking?" } %></p>
        <% end %>
      </div>
    </div>
  </section>

  <section id="content3">
    <p>
      Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
    </p>
    <p>
      Brisket meatball turkey short loin boudin leberkas meatloaf chuck andouille pork loin pastrami spare ribs pancetta rump. Frankfurter corned beef beef tenderloin short loin meatloaf swine ground round venison.
    </p>
  </section>

</main>
>>>>>>> Stashed changes

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class="row forms">
  <div class="col-xs-4 col-xs-offset-4">
    <h1>edit item!</h1>
      <%= simple_form_for @item do |i| %>
        <%= i.input :name, placeholder: "Catchy name for your item" %>
        <%= i.input :category, collection: ["bags", "jewellery", "fine watches", "belts", "ties", "glasses", "hats", "pocket squares", "cufflinks"] %>
        <%= i.input :description, as: :text, placeholder: "Write about how dapper your item is. The better the description, the more likely it will be booked!" %>
        <%= i.input :condition, as: :radio_buttons, collection: ["perfect", "very good", "good", "worn well"] %>
        <%= i.input :brand %>
        <%= i.input :price, label: "Price Per Day (￥)" %>
        <%= i.button :submit, class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="search-container">
<!--   <div class="row"> -->
<!--     <div class="col col-sm-4"> -->
      <form action="/items" method="get" class="filters">
        <div>
          <h1>Refine Your Search</h1>
        </div>
        <div class="search-inputs">
          <select name="category" id="category_select">
            <option value="">CATEGORY</option>
            <% Item.categories.each do|category|%>
              <option value="<%= category %>"<%= category == @preselect[:category] ? "selected" : "" %> > <%= category.capitalize %></option>
            <% end %>
          </select>
          <input type="hidden" name="search" value=<%= params[:search] %> >
          <select name="brand" id="brand_select">
            <option value="">BRAND</option>
            <% Item.brands.each do|brand|%>
              <option value="<%= brand %>"<%= brand == @preselect[:brand] ? "selected" : "" %> > <%= brand.capitalize %></option>
            <% end %>
          </select>
          <select name="condition" id="condition_select">
            <option value="">CONDITION</option>
            <% Item.conditions.each do|condition|%>
              <option value="<%= condition %>" > <%= condition.capitalize %></option>
            <% end %>
          </select>
        </div>
  <!--       <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button> -->
        <div class="submit-filter">
          <input type="submit" class="btn btn-primary">
        </div>
      </form>
<!--     </div> -->
<!--   </div> -->
</div>

<div class="search-banner">
  <%= image_tag "search-banner.png", class: "search-banner-image" %>
</div>


<div class="container cards">
  <div class="row">
    <% @items.each do |item| %>
    <div class="col col-xs-12 col-sm-4">
      <%= link_to item_path(item), class: "card-link" do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= item.photo? ? (cl_image_path item.photo.path) : (image_path 'Flatlay.JPG') %>');">
      <% end %>
        <div class="card-category"><%= item.name %></div>
      </div>
      <div class="card-info">
        <p><%= item.brand %></p>
        <p>￥<%= item.price %>/day</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="row forms">
  <div class="col-xs-4 col-xs-offset-4">
    <h1>add a new item!</h1>
      <%= simple_form_for @item do |i| %>
        <%= i.input :name %>
        <%= i.input :category, collection: ["bags", "jewellery", "fine watches", "belts", "ties", "shades", "hats", "pocket squares", "cufflinks"] %>
        <%= i.input :description, as: :text, placeholder: "Write about how dapper your item is. The better the description, the more likely it will be booked!" %>
        <%= i.input :condition, as: :radio_buttons, collection: ["perfect", "very good", "good", "worn well"]%>
        <%= i.input :brand %>
        <%= i.input :price, label: "Price Per Day (in RMB)" %>
        <%= i.input :photo, as: :attachinary %>
        <%= i.button :submit, class:"btn-add" %>
      <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="item">
    <div class="item-info">
      <%= image_tag cl_image_path @item.photo.path %>
      <h1><%= @item.name %></h1>
      <div class="item-icons">
        <p><i class="fa fa-filter" aria-hidden="true"></i> <%= @item.category %></p>
        <p><i class="fa fa-tag" aria-hidden="true"></i> <%= @item.brand %></p>
        <p><i class="fa fa-star" aria-hidden="true"></i> <%= @item.condition %></p>
      </div>
      <h3>Description</h3>
      <p><%= @item.description %></p>
      <div class = "add-item">
        <%= link_to "Go Back", :back, class: "btn btn-primary" %>
      </div>
    </div>

    <div class="booking">
      <div class="price-review">
      <p>￥<%= @item.price %></p><p> /per day</p>
      </div>
      <div class="calendars">
        <h3>Book it. Be dapper.</h3>
        <%= simple_form_for [@item, @booking] do |i| %>
          <%= i.input :start_date, as: :string, input_html: {class: 'datepicker'} %>
          <%= i.input :end_date, as: :string, input_html: {class: 'datepicker'}%>
          <%= i.button :submit, class: "btn btn-primary" %>
          <% end %>
      </div>
      <div id="map" style="width: 233px; height: 265px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
                    var style = [
              {
                  "featureType": "road",
                  "stylers": [
                      {
                          "hue": "#5e00ff"
                      },
                      {
                          "saturation": -79
                      }
                  ]
              },
              {
                  "featureType": "poi",
                  "stylers": [
                      {
                          "saturation": -78
                      },
                      {
                          "hue": "#6600ff"
                      },
                      {
                          "lightness": -47
                      },
                      {
                          "visibility": "off"
                      }
                  ]
              },
              {
                  "featureType": "road.local",
                  "stylers": [
                      {
                          "lightness": 22
                      }
                  ]
              },
              {
                  "featureType": "landscape",
                  "stylers": [
                      {
                          "hue": "#6600ff"
                      },
                      {
                          "saturation": -11
                      }
                  ]
              },
              {},
              {},
              {
                  "featureType": "water",
                  "stylers": [
                      {
                          "saturation": -65
                      },
                      {
                          "hue": "#1900ff"
                      },
                      {
                          "lightness": 8
                      }
                  ]
              },
              {
                  "featureType": "road.local",
                  "stylers": [
                      {
                          "weight": 1.3
                      },
                      {
                          "lightness": 30
                      }
                  ]
              },
              {
                  "featureType": "transit",
                  "stylers": [
                      {
                          "visibility": "simplified"
                      },
                      {
                          "hue": "#5e00ff"
                      },
                      {
                          "saturation": -16
                      }
                  ]
              },
              {
                  "featureType": "transit.line",
                  "stylers": [
                      {
                          "saturation": -72
                      }
                  ]
              },
              {}
          ];
          var handler = Gmaps.build('Google');
          handler.buildMap({
            provider: { styles: style},
            internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(8);
            }
          });
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>